### PR TITLE
Update conanfile.py

### PR DESCRIPTION
**Pull request by memsharded**
The / notation has issues when consumed by the cmake generator using the TARGETS approach, as they are put into INTERFACE_LINK_LIBRARIES are treated as files instead of flags by cmake. Replacing with "-" seems to be good for all cases.

### CODE REVIEW

**Comment by sixten-hilborn** [comment]
I've seen `/NODEFAULTLIB` in other libs in this repo too, would be nice to replace all of them with `-NODEFAULTLIB`.

**Comment by dimi309** [comment]
Understood. Thanks @memsharded !
@sixten-hilborn I'll go through all the packages and replace the rest of the slashes. Many thanks for the feedback!

**Comment by dimi309** [comment]
@sixten-hilborn @memsharded  Ok, I've changed them everywhere. Let me know if you have any further suggestions or questions. The changes will be available on bintray as well, as soon as the travis & appveyor builds are competed. glfw builds for osx/macos fail online because of a peculiarity I've recently discovered. I'll fix it, but in the meantime note that they work if you run them on a local workstation.

**Comment by memsharded** [comment]
Excellent, thank you!

**Comment by dimi309** [comment]
The latest changes were not being reflected on bintray because the OSX problem of glfw was blocking the uploads of many packages. That has been corrected now and the packages are up to date, also on bintray.

**Comment by memsharded** [comment]
Thanks again, good job :)

**Comment by dimi309** [comment]
Thank you, for the advice!

**Pull request merged**
